import Head from "next/head";
import FixedMenuLayout from "@/components/SemanticLayoutExample";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            <a href="https://nextjs.org">Next.js! </a>with Semantic-UI
          </h1>
          <p className={styles.description}>
            Scroll to see the Semantic-UI layout
          </p>
          <br />
          <code className={styles.code}>
            Don't forget to edit <b>index.js </b>later
          </code>
        </main>
      </div>
      <FixedMenuLayout />
    </>
  );
}
